---

- name: Install psycopg2 into the system Python site, so that Ansible modules can use it
  become: yes
  pip: name=psycopg2 state=present

- name: Create MolDB postgres user
  postgresql_user: name=mol_db password={{ mol_db_postgres_pass }} role_attr_flags=CREATEDB
  become: yes
  become_user: postgres

- name: Create MolDB postgres database
  become: yes
  become_user: postgres
  postgresql_db: name=mol_db owner=mol_db encoding=UTF8 template=template0

- name: Check if env already exists
  stat:
    path: "{{ mol_db_miniconda_prefix }}/envs/{{ mol_db_miniconda_env.name }}"
  register: env_status

- name: Create conda environment (from environment.yml file) if it doesn't exist
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: "conda env create"
  when: not env_status.stat.exists

- name: Update conda environment (from environment.yml file) if it exists
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: "conda env update -f environment.yml"
  when: env_status.stat.exists

- name: Install OpenBabel
  apt: name=openbabel state=latest
  become: yes

- name: Install openbabel into conda environment
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: >
    source {{ mol_db_miniconda_prefix }}/bin/activate {{ mol_db_miniconda_env.name }}
    && conda install -c openbabel openbabel

- import_tasks: import_mol_databases.yml
  when: mol_db_import_databases

- import_tasks: import_mol_images.yml
  when: mol_db_import_mol_images
