name: mol-db
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- nomkl
- python=3.6
- cairo=1.14.8=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gunicorn=19.1.0
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libpq=9.5.4=0
- libxml2=2.9.4=0
- numpy=1.11.3
- openbabel::openbabel=2.4.1
- openssl=1.0.2k=2
- pandas=0.19.2
- pastedeploy=1.5.2
- pip=9.0.1
- pixman=0.34.0=0
- psycopg2=2.6.2
- python-dateutil=2.6.0
- pytz=2017.2
- readline=6.2=2
- setuptools=27.2.0
- six=1.10.0
- sqlalchemy=1.1.5
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - cffi==1.10.0
  - cpymspec==0.3.5
  - falcon==1.1.0
  - pycparser==2.17
  - pymspec==0.1.2
  - python-mimeparse==1.6.0
