sm_home: "{{ metaspace_home }}/metaspace/engine"
sm_miniconda_prefix: /opt/dev/miniconda3
sm_miniconda_env_name: sm
sm_activate_venv: source {{ sm_miniconda_prefix }}/bin/activate {{ sm_miniconda_env_name }}
