---
- name: Install OpenJDK JRE (headless)
  apt: pkg=openjdk-{{ java_major_version }}-jre-headless={{ java_version }}
       state=present

- name: Install OpenJDK JRE
  apt: pkg=openjdk-{{ java_major_version }}-jre={{ java_version }}
       state=present

- name: Install OpenJDK
  apt: pkg=openjdk-{{ java_major_version }}-jdk={{ java_version }}
       state=present

- name: Determine if 64bit architecture
  set_fact:
    ansible_architecture: amd64
  when: ansible_architecture == "x86_64"

- name: Set OpenJDK as the default
  alternatives: name=java path="/usr/lib/jvm/java-{{ java_major_version }}-openjdk-{{ ansible_architecture }}/jre/bin/java"
