---

- name: SM services instance basic configuration
  hosts: web
  user: ubuntu
  gather_facts: no

  roles:
    - role: base
      become: yes
      swapsize: 16384

  tasks:
    - name: Add spark master public key to authorized_keys
      authorized_key: user=ubuntu key="{{ item }}"
      with_file:
        - "{{ spark_key_file }}.pub"
  tags: [base]


- name: SM services instance configuration
  hosts: web
  user: ubuntu
  gather_facts: yes

  pre_tasks:
    - name: Gather EC2 instance facts
      ec2_metadata_facts:
      tags: [always]

  roles:
    - role: postgres
      become: yes
      tags: [postgres]

    - role: elasticsearch
      become: yes
      tags: [elasticsearch]

    - role: kibana
      become: yes
      tags: [kibana]

    - role: nginx
      tags: [nginx]

    - role: rabbitmq
      tags: [rabbitmq]

    - role: miniconda
      tags: [miniconda]

    - role: supervisor
      tags: [supervisor]

    - role: nodejs
      tags: [nodejs]

    - role: sm_web
      tags: [sm-web]
