- name: Create directory for molecular structure images
  become: yes
  file: path={{ mol_db_image_dir }} state=directory owner=ubuntu group=ubuntu

- name: Copy molecular structure images
  become: yes
  unarchive:
    src: "{{ item }}"
    dest: "{{ mol_db_image_dir }}"
    remote_src: True
    owner: ubuntu
    group: ubuntu
  with_items: "{{ mol_db_image_archives }}"
