name: sm_engine
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy=1.11.2
  - scipy=0.18.1
  - matplotlib=2
  - pandas>=0.22
  - cffi
  - libgcc
  - psycopg2=2.7.1
  - pytest
  - nomkl
  - pip:
    - Fabric3
    - requests
    - pytest
    - recommonmark
    - boto3
    - fabric3
    - pypng
    - pyyaml
    - elasticsearch
    - elasticsearch_dsl
    - pika>=0.11.0b1
    - coverage
    - codecov
    - bottle
    - pyspark==2.3.0
    - pysparkling
    - PyArrow>=0.8.0
    - Pillow==4.2.1
    - pyopenms==2.2.0
    - pysparkling
