---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    components: ''

  tasks:
    - name: Stopping SM cluster instances
      shell: python3 aws_instance_manager.py stop --key-name {{ aws_key_name }}
             --components {{ components }} --stage {{ stage }} --region {{ aws_region }}
