---

elasticsearch_version: "{{ elk_version }}"
kibana_version: "{{ elk_version }}"
kibana_es_port: "{{ elasticsearch_port }}"

nginx_raw_config: |
  server {
      listen 80 default_server;
      listen [::]:80 default_server;
      #server_name elk.metasp.us
      return 301 https://$server_name$request_uri;
  }

  server {
      # SSL configuration
      listen 443 ssl http2 default_server;
      listen [::]:443 ssl http2 default_server;
      include snippets/ssl-elk.metasp.us.conf;
      include snippets/ssl-params.conf;

      auth_basic "Restricted Access";
      auth_basic_user_file /etc/nginx/.htpasswd;

      location / {
          proxy_pass http://localhost:5601;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  }

  server {
      listen 9200;

      auth_basic "Restricted Access";
      auth_basic_user_file /etc/nginx/.htpasswd;

      location / {
          proxy_pass http://localhost:{{ elasticsearch_port }};
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  }
