---

- name: Define supervisor_app name
  set_fact:
    app: "{{ supervisor_app | default('all') }}"

- debug: var=app

- name: Check if supervisord daemon is running
  shell: supervisorctl status
  args:
    executable: /bin/bash
  register: supervisorctl_status_out

- name: Start supervisord daemon
  shell: >
    supervisord -c /etc/supervisor/supervisord.conf -l /var/log/supervisor/supervisord.log
    && supervisorctl stop all
  args:
    executable: /bin/bash
  register: command_result
  when: "'no such file' in supervisorctl_status_out.stdout"

- name: "Restart {{ app }} app(s) running under supervisor"
  shell: >
    supervisorctl reread
    && supervisorctl update
    && supervisorctl restart {{ app }}
  args:
    executable: /bin/bash

- name: Check {{ app }} app(s) status
  shell: supervisorctl status {{ app }}
  args:
    executable: /bin/bash
  register: res
  failed_when: '"EXITED" in res.stdout or "FATAL" in res.stdout or "ERROR" in res.stdout or "BACKOFF" in res.stdout'
