---

- name: Download Filebeat version={{ filebeat_version }}
  get_url: url=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb
           dest=/tmp/filebeat-{{ filebeat_version }}.deb

- name: Install Filebeat
  command: dpkg -i /tmp/filebeat-{{ filebeat_version }}.deb

- name: Create /etc/filebeat/filebeat.yml template
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml mode=0644

- name: Create Elasticsearch ingest node pipelines
  uri:
    url: http://{{ es_host }}:9200/_ingest/pipeline/{{ ingest_node_pipeline_id }}
    method: PUT
    user: "{{ es_user }}"
    password: "{{ es_password }}"
    body: "{{ ingest_node_pipeline | to_json }}"
    body_format: json

- name: Filebeat conf update restart
  service: name=filebeat state=restarted

- name: Start Filebeat service
  service: name=filebeat state=started

- name: Start Filebeat on boot
  service: name=filebeat enabled=true
