---

- name: Uninstall SM from conda environment
  args:
    chdir: "{{ sm_home }}"
    executable: /bin/bash
  shell: "{{ sm_activate_venv }} && pip uninstall -y sm"
  ignore_errors: yes

- name: Install SM into conda environment
  args:
    chdir: "{{ sm_home }}"
    executable: /bin/bash
  shell: "{{ sm_activate_venv }} && pip install ."

- name: Pull SM config from the remote host
  fetch: src={{ sm_home }}/conf/config.json.template dest=/tmp/config.json.template
         flat=yes fail_on_missing=yes

- name: "Put SM config to {{ sm_home }}/conf/config.json"
  template: src=/tmp/config.json.template dest={{ sm_home }}/conf/config.json
            owner={{ spark_user }} group={{ spark_user }} mode=0600

- name: Make sure that a directory for the SM logs exists
  file: path={{ sm_home }}/logs state=directory mode=0755
