---

- name: ELK instance configuration
  hosts: elk
  user: ubuntu
  gather_facts: no

  tasks:
    - name: Install python-simplejson
      become: yes
      raw: apt-get update && apt-get install -y python-simplejson


- name: Install and configure ES, Kibana, Nginx
  hosts: elk
  user: ubuntu
  gather_facts: yes

  roles:
    - role: base
      tags: [base]

    - role: elk
      nginx_server_name: "{{ ansible_ec2_public_ipv4 }}"
      basic_auth_users: "{{ elk_basic_auth_users }}"
      tags: [elk]
